### ISSUE TITLE
error upon analyzing, cannot find Delphi sources (custom install path)

### ISSUE THREAD

**Issue by Khorkhe** [integrated-application-development/delphilint#13]
### Prerequisites

- [X] This bug is in DelphiLint, not SonarDelphi, SonarQube, or my Delphi code.
- [X] This bug has not already been reported.

### Delphi IDE version

11.3

### DelphiLint version

1.0.0

### SonarDelphi version

1.3

### Issue description

An error was raised (au.com.integradev.delphi.symbol.SymbolTableBuilder$SymbolTableConstructionException: Path to Delphi standard library is invalid: C:\Program Files (x86)\Embarcadero\Studio\22.0\source

I have Delphi installed in a custom directory.
How can I instruct DelphiLint where to find by Delphi sources folder?  Shouldn't it be reading that from some BDS environment variable?

### Steps to reproduce

install Delphi in a custom directory.

**Comment by Cirras** [comment]
Hi @Khorkhe,

That issue should be fixed as of #11.
Please try the [DelphiLint 1.0.1](https://github.com/integrated-application-development/delphilint/releases/tag/v1.0.1) release and let us know if your issue is resolved.

**Comment by Khorkhe** [comment]
installed v1.0.1, resolved. thank you.
