### ISSUE TITLE
Add old Delphi support if possible

### ISSUE THREAD

**Issue by Makhaon** [integrated-application-development/delphilint#14]
### Prerequisites

- [X] This improvement has not already been suggested.
- [X] This improvement would be generally useful, not specific to my code or setup.

### Engine area

Delphi IDE integration

### Improvement description

Add old Delphi support if possible, at least down to Delphi 10 Berlin.

### Rationale

Many people use old Delphi IDEs

**Comment by code-kungfu** [comment]
I don't think you should expect this.

The IDE integration relies on new editor drawing APIs introduced in 11.3 and getting that to work reliably in older Delphi versions would be quite a workload IMO (Speaking as someone who write IDE plugins myself).

The question would be, what is holding back from upgrading to a more recent Delphi version?

**Comment by fourls** [comment]
As @code-kungfu says, it isn't feasible for DelphiLint to support earlier versions because the editor API has historically been significantly lacking.

DelphiLint actually intentionally does not use the Delphi 11.3 editor drawing APIs, so we can support all Delphi 11 versions. That being said, it uses other features that are not available in older editions.

For example, the rule description view uses the TEdgeBrowser component, which is the only practical way to have a modern webview embed without introducing more external dependencies. TEdgeBrowser was introduced in Delphi 10.4, so as a hard limit we are unable to support versions lower than that.

If there are any relatively simple adjustments that can be made to make it easier to build the project yourself on your desired Delphi version, these might be considered, but we're not intending to officially support any version lower than Delphi 11.

**Comment by andrevfarias** [comment]
I made the required adjustments and made it work in Delphi 10.2.3 Tokyo.
By creating a second ToolFrame (Legacy) using TListView and TWebBrowser and some minor changes in some other units I could make it work very well.
I would appreciate colaborating with the project.
Could I create a pull request with all the cnanges to be analyzed?

**Comment by adrianosantostreina** [comment]
> Fiz os ajustes necessários e fiz funcionar em Delphi 10.2.3 Tokyo. Criando um segundo ToolFrame (Legacy) usando TListView e TWebBrowser e algumas pequenas alterações em algumas outras unidades EU poderia fazer funcionar muito bem. Apreciaria colaborar com o projeto. Eu poderia criar um pull request com todos os cnanges a serem analisados?


> I don't think you should expect this.
> 
> The IDE integration relies on new editor drawing APIs introduced in 11.3 and getting that to work reliably in older Delphi versions would be quite a workload IMO (Speaking as someone who write IDE plugins myself).
> 
> The question would be, what is holding back from upgrading to a more recent Delphi version?

With all due respect, you live on another planet; you have no idea how many developers and companies use older versions of Delphi. In Brazil, especially, licenses are extremely expensive, and many companies have legacy systems that present several obstacles to upgrading to newer versions. And I'm not even talking about versions that are that old.

If the plugin supported at least versions after Embarcadero's acquisition of Borland, it would already be interesting. Delphi XE5 and later would already be very interesting and would serve thousands of companies in Brazil.

Just a tip.

**Comment by adrianosantostreina** [comment]
> I made the required adjustments and made it work in Delphi 10.2.3 Tokyo. By creating a second ToolFrame (Legacy) using TListView and TWebBrowser and some minor changes in some other units I could make it work very well. I would appreciate colaborating with the project. Could I create a pull request with all the cnanges to be analyzed?

André, I would like to test your version for Delphi Tokyo, it should possibly work in Rio too.

**Comment by fourls** [comment]
Hi @adrianosantostreina,

The primary point of those comments is that there is a significant maintenance cost to officially supporting versions of Delphi that are many years and several major versions out of date. This is a FOSS tool we have developed that has been open-sourced for the community to use and contribute to, and we have no obligations to appeal to the broadest possible customer base if it comes with a significant ongoing maintenance and development burden.

None of the maintainers use a Delphi version lower than 11, and so we wouldn't ever be able to guarantee official support for versions below that - we don't have the tooling to compile it for all versions, let alone properly test it. We appreciate that DelphiLint might still be useful for older Delphi versions - as I said in my earlier comment:

> If there are any relatively simple adjustments that can be made to make it easier to build the project yourself on your desired Delphi version, these might be considered, but we're not intending to officially support any version lower than Delphi 11.

**Comment by fourls** [comment]
> I made the required adjustments and made it work in Delphi 10.2.3 Tokyo. By creating a second ToolFrame (Legacy) using TListView and TWebBrowser and some minor changes in some other units I could make it work very well. I would appreciate colaborating with the project. Could I create a pull request with all the cnanges to be analyzed?

Hi @andrevfarias, apologies - I must have missed this message in June. We are always open for PRs so please raise your pull request, thank you :)

It's worth noting that (for the reasons I've outlined above) the prospect of maintaining an entire second copy of the project's largest form is not particularly appealing, although I'm more than happy to take a look.

**Comment by adrianosantostreina** [comment]
> Hi [@adrianosantostreina](https://github.com/adrianosantostreina),
> 
> The primary point of those comments is that there is a significant maintenance cost to officially supporting versions of Delphi that are many years and several major versions out of date. This is a FOSS tool we have developed that has been open-sourced for the community to use and contribute to, and we have no obligations to appeal to the broadest possible customer base if it comes with a significant ongoing maintenance and development burden.
> 
> None of the maintainers use a Delphi version lower than 11, and so we wouldn't ever be able to guarantee official support for versions below that - we don't have the tooling to compile it for all versions, let alone properly test it. We appreciate that DelphiLint might still be useful for older Delphi versions - as I said in my earlier comment:
> 
> > If there are any relatively simple adjustments that can be made to make it easier to build the project yourself on your desired Delphi version, these might be considered, but we're not intending to officially support any version lower than Delphi 11.

I don't currently use previous versions either, but my consulting clients do. Anyway. I understand that it's not your core business, so keeping the plugin in previous versions doesn't bring any benefits.

A colleague here at ISSUEs mentioned that he compiled it for Delphi Tokyo. If authorized, he could fork the project, publish it, and give due credit. I don't know if the license allows this.

Anyway, if it's within my reach, I can try compiling it in Delphi Rio and validating it.

**Comment by andrevfarias** [comment]
Thanks @adrianosantostreina and @fourls for your responses.
I’ve just submitted a pull request ([#101](https://github.com/integrated-application-development/delphilint/pull/101)) and I’m sharing my fork, which includes all the adjustments for Delphi Tokyo compatibility: [github.com/andrevfarias/delphilint](https://github.com/andrevfarias/delphilint).
It was made with a focus on Tokyo, but I believe it can be adapted to other versions as well.
Feedback and contributions are welcome.

**Comment by adrianosantostreina** [comment]
> Thanks [@adrianosantostreina](https://github.com/adrianosantostreina) and [@fourls](https://github.com/fourls) for your responses. I’ve just submitted a pull request ([#101](https://github.com/integrated-application-development/delphilint/pull/101)) and I’m sharing my fork, which includes all the adjustments for Delphi Tokyo compatibility: [github.com/andrevfarias/delphilint](https://github.com/andrevfarias/delphilint). It was made with a focus on Tokyo, but I believe it can be adapted to other versions as well. Feedback and contributions are welcome.

Thanks, I'll download your fork and test it in Rio. I'll let you know how it goes.
