### ISSUE TITLE
CPU usage when Delphi is idle

### ISSUE THREAD

**Issue by JonRobertson** [integrated-application-development/delphilint#20]
### Prerequisites

- [X] This bug is in DelphiLint, not SonarDelphi, SonarQube, or my Delphi code.
- [X] This bug has not already been reported.

### Delphi IDE version

Delphi 11 Version 28.0.48361.3236

### DelphiLint version

1.0.1

### SonarDelphi version

1.3.0

### Issue description

The Delphi / RAD Studio IDE (BDS.exe) continually races one CPU even when the IDE is idle and no projects are open.

### Steps to reproduce

With DelphiLint previously installed in Delphi 11, launch Delphi.
Open Task Manager and monitor the CPU usage for BDS.exe.

My laptop has 12 logical processors. BDS.exe runs at a constant 8% when I am not doing anything in the IDE, or on the laptop. I have not even opened a project in Delphi.

In Delphi, select Component, Install Packages, and remove Delphi Lint. The CPU usage for BDS.exe immediately drops to 0% once Delphi Lint is removed.

**Comment by fourls** [comment]
Hi @JonRobertson,

Thanks for raising this issue. I've reproduced and am investigating.
