### ISSUE TITLE
Compatibility for Delphi 12?

### ISSUE THREAD

**Issue by kiviancristaldo** [integrated-application-development/delphilint#38]
### Prerequisites

- [X] This question has not already been answered.

### Inquiry

Hi!

This componente will be a compatibility for Delphi 12?

Thanks!!

**Comment by Cirras** [comment]
Hi @kiviancristaldo,

Yes, DelphiLint is compatible with Delphi 12. 👍
See the `DelphiLint-*-12Athens.zip` file on the [latest release](https://github.com/integrated-application-development/delphilint/releases/latest).
